# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "median", # <get_performance>
  "mad", # <get_performance>
  "value", # <plot_evaluation>
  "importance", # <plot_importance>
  "variable", # <plot_importance>
  "distance.threshold", # <plot_moran>
  "moran.i", # <plot_moran>
  "p.value.binary", # <plot_moran>
  "repetition", # <plot_moran>
  "moran.i", # <plot_optimization>
  "r.squared", # <plot_optimization>
  "optimization", # <plot_optimization>
  "spatial.predictor.index", # <plot_optimization>
  "x", # <plot_residuals_diagnostics>
  "y", # <plot_residuals_diagnostics>
  "Predicted", # <plot_residuals_diagnostics>
  "Residuals", # <plot_residuals_diagnostics>
  "median", # <plot_response_curves>
  "quantile", # <plot_response_curves>
  "distance.threshold", # <plot_training_df_moran>
  "moran.i", # <plot_training_df_moran>
  "p.value.binary", # <plot_training_df_moran>
  "metric", # <plot_tuning>
  "value", # <plot_tuning>
  "Predicted", # <residuals_diagnostics>
  "Residuals", # <residuals_diagnostics>
  "model", # <rf_compare>
  "value", # <rf_compare>
  "importance", # <rf_importance>
  "variable", # <rf_importance>
  "importance.mad", # <rf_importance>
  "y", # <rf_interactions>
  "median", # <rf_repeat>
  NULL
))
