#' @title Plots a Moran's I test of model residuals
#' @description Plots the results of spatial autocorrelation tests for a variety of functions within the package. The x axis represents the Moran's I estimate, the y axis contains the values of the distance thresholds, the dot sizes represent the p-values of the Moran's I estimate, and the red dashed line represents the theoretical null value of the Moran's I estimate.
#' @usage
#' plot_moran(
#'   model,
#'   option = 1,
#'   verbose = TRUE
#' )
#' @param model A model fitted with [rf()], [rf_repeat()], or [rf_spatial()], or a data frame generated by [moran()]. Default: `NULL`
#' @param option Integer, type of plot. If `1` (default) a line plot with Moran's I and p-values across distance thresholds is returned. If `2`, scatterplots of residuals versus lagged residuals per distance threshold and their corresponding slopes are returned. In models fitted with [rf_repeat()], the residuals and lags of the residuals are computed from the median residuals across repetitions. Option `2` is disabled if `x` is a data frame generated by [moran()].
#' @param verbose Logical, if `TRUE`, the resulting plot is printed, Default: `TRUE`
#' @return A ggplot.
#' @seealso [moran()], [moran_multithreshold()]
#' @examples
#' \donttest{
#' if(interactive()){
#'
#'  data(plant_richness_df)
#'  data(distance.matrix)
#'
#'  rf.model <- rf(
#'    data = plant_richness_df,
#'    dependent.variable.name = "richness_species_vascular",
#'    predictor.variable.names = colnames(plant_richness_df)[5:21],
#'    distance.matrix = distance_matrix,
#'    distance.thresholds = c(0, 1000, 2000),
#'    verbose = FALSE
#'  )
#'
#'  #line plot
#'  plot_moran(rf.model)
#'
#'  #scatterplot
#'  plot_moran(rf.model, option = 2)
#'
#' }
#' }
#' @rdname plot_moran
#' @export
#' @importFrom ggplot2 ggplot aes geom_hline geom_point geom_line xlab ylab ggtitle theme labs scale_colour_manual
#' @export
plot_moran <- function(
  model = NULL,
  option = 1,
  verbose = TRUE
  ){

  #checking option
  if(!(option %in% c(1, 2)) |
     inherits(model, "data.frame")){
    option <- 1
  }

  #option 1
  if(option == 1){

    #declaring variables
    distance.threshold <- NULL
    moran.i <- NULL
    moran.i.null <- NULL
    p.value.binary <- NULL
    repetition <- NULL

    if(!inherits(model, "data.frame")){
      #importance from rf_repeat
      if(inherits(model, "rf_repeat")){
        x <- model$residuals$autocorrelation$per.repetition
      } else {
        x <- model$residuals$autocorrelation$per.distance
      }
    } else {
      x <- model
    }

    #adding binary p.value
    x$p.value.binary <- "< 0.05"
    x[x$p.value >= 0.05, "p.value.binary"] <- ">= 0.05"
    x$p.value.binary <- factor(x$p.value.binary, levels = c("< 0.05", ">= 0.05"))

    #plotting rf
    if(!("repetition" %in% colnames(x))){

      p1 <- ggplot2::ggplot(data = x) +
        ggplot2::aes(
          x = distance.threshold,
          y = moran.i,
          size = p.value.binary
        ) +
        ggplot2::geom_point(color = "gray25") +
        ggplot2::geom_line(size = 1, color = "gray25") +
        ggplot2::geom_hline(
          yintercept = 0,
          col = "gray50",
          size = 0.5,
          linetype = "dotted"
        ) +
        ggplot2::geom_hline(
          yintercept = x$moran.i.null[1],
          col = "red4",
          size = 0.7,
          linetype = "dashed"
        ) +
        ggplot2::scale_size_manual(
          breaks = c("< 0.05", ">= 0.05"),
          values = c(2.5, 5),
          drop = FALSE
        ) +
        ggplot2::scale_x_continuous(breaks = x$distance.threshold) +
        ggplot2::xlab("Distance thresholds") +
        ggplot2::ylab("Moran's I of model residuals") +
        ggplot2::ggtitle("Multiscale Moran's I") +
        ggplot2::theme_bw() +
        ggplot2::theme(legend.position = "bottom") +
        ggplot2::labs(size = "Moran's I p-value") +
        ggplot2::theme(plot.title = element_text(hjust = 0.5))

    } else {

      p1 <- ggplot2::ggplot(data = x) +
        ggplot2::aes(
          x = distance.threshold,
          y = moran.i,
          group = repetition,
          size = p.value.binary
        ) +
        ggplot2::geom_point(
          color = "gray25",
          alpha = 0.7
        ) +
        ggplot2::geom_line(
          size = 1,
          color = "gray25",
          alpha = 0.7
        ) +
        ggplot2::geom_hline(
          yintercept = 0,
          col = "red4",
          size = 0.7,
          linetype = "dashed"
        ) +
        ggplot2::scale_size_manual(
          breaks = c("< 0.05", ">= 0.05"),
          values = c(2.5, 5),
          drop = FALSE
        ) +
        ggplot2::scale_x_continuous(breaks = x$distance.threshold) +
        ggplot2::xlab("Distance thresholds") +
        ggplot2::ylab("Moran's I of residuals") +
        ggplot2::ggtitle("Moran's I of the residuals") +
        ggplot2::theme_bw() +
        ggplot2::theme(legend.position = "bottom") +
        ggplot2::labs(color = "Model", size = "Moran's I p-value")

    }

    if(verbose == TRUE){
      suppressWarnings(print(p1))
    }

    return(p1)

  }#end of option == 1

  #option 2
  if(option == 2){

    residual <- NULL
    residual.lag <- NULL

    #getting residuals
    m.residuals <- model$residuals$values

    #getting distance matrix
    if(!is.null(model$ranger.arguments$distance.matrix)){
      distance.matrix <- model$ranger.arguments$distance.matrix
    } else {
      stop("distance.matrix not found in model$ranger.arguments")
    }

    #getting distance thresholds
    if(!is.null(model$ranger.arguments$distance.thresholds)){
      distance.thresholds <- model$ranger.arguments$distance.thresholds
    } else {
      stop("distance.matrix not found in x$ranger.arguments")
    }

    #getting Moran's I results
    m.moran <- model$residuals$autocorrelation$per.distance

    #iterating through distance thresholds
    loop.out <- foreach::foreach(distance.threshold = distance.thresholds) %do% {

      #matrix of weights
      distance.weights <- weights_from_distance_matrix(
        distance.matrix = distance.matrix,
        distance.threshold = distance.threshold
      )

      #computing weighted mean of the lag
      residuals.lag <- apply(
        X = distance.weights,
        MARGIN = 1,
        FUN = function(x){x %*% m.residuals}
      )

      #subset moran i
      moran.i <- round(m.moran[m.moran$distance.threshold == distance.threshold, "moran.i"], 3)
      p.value <- round(m.moran[m.moran$distance.threshold == distance.threshold, "p.value"], 4)

      #label for facet
      facet.label <- paste0(
        "Distance = ",
        distance.threshold,
        "   Moran's I = ",
        moran.i,
        "   p-value = ",
        p.value
      )

      #out data frame
      out.df <- data.frame(
        distance.threshold = rep(facet.label, length(m.residuals)),
        residual = m.residuals,
        residual.lag = residuals.lag
      )

    }

    #to df
    plot.df <- do.call(
      "rbind",
      loop.out
    )

    #plot
    p2 <- ggplot2::ggplot(data = plot.df) +
      ggplot2::theme_bw() +
      ggplot2::facet_wrap(
        "distance.threshold",
        ncol = 1) +
      ggplot2::aes(
        x = residual,
        y = residual.lag,
        color = residual + residual.lag
      ) +
      ggplot2::geom_point(alpha = 0.75) +
      ggplot2::geom_hline(
        yintercept = 0,
        color = "black",
        linetype = "dotted"
      ) +
      ggplot2::scale_color_viridis_c(
        end = 0.9
      ) +
      ggplot2::geom_smooth(
        method = "lm",
        color = "gray30",
        fill = "gray50",
        se = TRUE,
        alpha = 0.2,
        formula = y ~ x,
        size = 0.6
      ) +
      ggplot2::coord_fixed(expand = FALSE) +
      ggplot2::xlab("Model residual") +
      ggplot2::ylab("Lag of the model residual") +
      ggplot2::theme(legend.position = "none")

    if(verbose == TRUE){
      suppressWarnings(print(p2))
    }

    return(p2)

  }

}
